/*
Copyright 2024 Upbound Inc.
*/

package controller

import (
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/upjet/v2/pkg/controller"
)

// SetupManual sets up controllers for manually implemented resources
// that are not generated by upjet.
func SetupManual(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		// Add manual controllers here.
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
