#!/bin/bash
# Post-generation script to add manual controller setup

CLUSTER_SETUP_FILE="internal/controller/cluster/zz_setup.go"
NAMESPACED_SETUP_FILE="internal/controller/namespaced/zz_setup.go"

echo "Adding manual controller setup to zz_setup.go files..."

add_manual_setup() {
    local setup_file="$1"

    # Check if the manual setup call already exists
    if grep -q "SetupManual" "$setup_file"; then
        echo "Manual setup already exists in $setup_file"
        return 0
    fi

    # Create a temporary file with proper line endings
    TEMP_FILE=$(mktemp)

    # Read the file and add the manual setup before each 'return nil' that closes
    # a Setup/SetupGated function (i.e. the ones preceded by a closing brace of the
    # for-loop). We track which function we are in and inject into both.
    awk '
    /^func Setup\(/ { in_setup = 1; in_setupgated = 0 }
    /^func SetupGated\(/ { in_setupgated = 1; in_setup = 0 }
    /^func / && !/^func Setup\(/ && !/^func SetupGated\(/ { in_setup = 0; in_setupgated = 0 }
    /^\treturn nil$/ && (in_setup || in_setupgated) {
        print ""
        print "\t// MANUAL CONTROLLER SETUP - DO NOT REMOVE"
        print "\t// Setup manual controllers that are not generated by upjet"
        print "\tif err := SetupManual(mgr, o); err != nil {"
        print "\t\treturn err"
        print "\t}"
        print "\t// END MANUAL CONTROLLER SETUP"
        in_setup = 0
        in_setupgated = 0
    }
    { print }
    ' "$setup_file" > "$TEMP_FILE"

    # Replace the original file with the temp file to maintain consistent line endings
    mv "$TEMP_FILE" "$setup_file"

    # Ensure consistent file permissions (644 - readable/writable by owner, readable by group/others)
    chmod 644 "$setup_file"

    echo "Manual controller setup added to $setup_file"
}

add_manual_setup "$CLUSTER_SETUP_FILE"
add_manual_setup "$NAMESPACED_SETUP_FILE"
