#!/bin/bash
# Post-generation script to add manual controller setup

SETUP_FILE="internal/controller/cluster/zz_setup.go"

echo "Adding manual controller setup to zz_setup.go..."

# Check if the manual setup call already exists
if grep -q "SetupManual" "$SETUP_FILE"; then
    echo "Manual setup already exists in zz_setup.go"
    exit 0
fi

# Store original file permissions
ORIGINAL_PERMS=$(stat -f "%Mp%Lp" "$SETUP_FILE" 2>/dev/null || stat -c "%a" "$SETUP_FILE" 2>/dev/null || echo "644")

# Create a temporary file with proper line endings
TEMP_FILE=$(mktemp)

# Read the file and add the manual setup before each 'return nil' that closes
# a Setup/SetupGated function (i.e. the ones preceded by a closing brace of the
# for-loop). We track which function we are in and inject into both.
awk '
/^func Setup\(/ { in_setup = 1; in_setupgated = 0 }
/^func SetupGated\(/ { in_setupgated = 1; in_setup = 0 }
/^func / && !/^func Setup\(/ && !/^func SetupGated\(/ { in_setup = 0; in_setupgated = 0 }
/^	return nil$/ && (in_setup || in_setupgated) {
    print ""
    print "	// MANUAL CONTROLLER SETUP - DO NOT REMOVE"
    print "	// Setup manual controllers that are not generated by upjet"
    print "	if err := SetupManual(mgr, o); err != nil {"
    print "		return err"
    print "	}"
    print "	// END MANUAL CONTROLLER SETUP"
    in_setup = 0
    in_setupgated = 0
}
{ print }
' "$SETUP_FILE" > "$TEMP_FILE"

# Replace the original file with the temp file to maintain consistent line endings
mv "$TEMP_FILE" "$SETUP_FILE"

# Ensure consistent file permissions (644 - readable/writable by owner, readable by group/others)
chmod 644 "$SETUP_FILE"

echo "Manual controller setup added to zz_setup.go"
