#!/bin/bash
# Post-generation script to add manual controller setup

set -euo pipefail

CLUSTER_SETUP_FILE="internal/controller/cluster/zz_setup.go"
NAMESPACED_SETUP_FILE="internal/controller/namespaced/zz_setup.go"

echo "Adding manual controller setup to zz_setup.go files..."

add_manual_setup() {
    local setup_file="$1"

    if [[ ! -f "$setup_file" ]]; then
        echo "Skipping missing generated setup file: $setup_file"
        return 0
    fi

    if grep -q "SetupManual" "$setup_file"; then
        echo "Manual setup already exists in $setup_file"
        return 0
    fi

    local temp_file
    temp_file=$(mktemp)

    awk '
    /^func Setup\(/ { in_setup = 1; in_setupgated = 0 }
    /^func SetupGated\(/ { in_setupgated = 1; in_setup = 0 }
    /^func / && !/^func Setup\(/ && !/^func SetupGated\(/ { in_setup = 0; in_setupgated = 0 }
    /^\treturn nil$/ && (in_setup || in_setupgated) {
        print ""
        print "\t// MANUAL CONTROLLER SETUP - DO NOT REMOVE"
        print "\t// Setup manual controllers that are not generated by upjet"
        print "\tif err := SetupManual(mgr, o); err != nil {"
        print "\t\treturn err"
        print "\t}"
        print "\t// END MANUAL CONTROLLER SETUP"
        in_setup = 0
        in_setupgated = 0
    }
    { print }
    ' "$setup_file" > "$temp_file"

    mv "$temp_file" "$setup_file"
    chmod 644 "$setup_file"

    echo "Manual controller setup added to $setup_file"
}

for setup_file in "$CLUSTER_SETUP_FILE" "$NAMESPACED_SETUP_FILE"; do
    add_manual_setup "$setup_file"
