/*
Copyright 2022 Upbound Inc.
*/

package controller

import (
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/upjet/v2/pkg/controller"

	costcenter "github.com/crossplane-contrib/provider-upjet-github/internal/controller/cluster/enterprise/costcenter"
)

// SetupManual sets up controllers for manually implemented resources
// that are not generated by upjet.
func SetupManual(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		costcenter.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
