// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HostedRunnerInitParameters struct {

	// Image configuration for the hosted runner. Cannot be changed after creation. Block supports:
	// Image configuration for the hosted runner. Cannot be changed after creation.
	Image []ImageInitParameters `json:"image,omitempty" tf:"image,omitempty"`

	// Whether this runner should be used to generate custom images. Cannot be changed after creation.
	ImageGen *bool `json:"imageGen,omitempty" tf:"image_gen,omitempty"`

	// The version of the runner image to deploy. This is only relevant for runners using custom images.
	// The version of the runner image to deploy. This is relevant only for runners using custom images.
	ImageVersion *string `json:"imageVersion,omitempty" tf:"image_version,omitempty"`

	// Maximum number of runners to scale up to. Runners will not auto-scale above this number. Use this setting to limit costs.
	// Maximum number of runners to scale up to.
	MaximumRunners *int64 `json:"maximumRunners,omitempty" tf:"maximum_runners,omitempty"`

	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain alphanumeric characters, '.', '-', and '_'.
	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to enable static public IP for the runner. Note there are account limits. To list limits, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/limits. Defaults to false.
	// Whether to enable static public IP.
	PublicIPEnabled *bool `json:"publicIpEnabled,omitempty" tf:"public_ip_enabled,omitempty"`

	// The ID of the runner group to assign this runner to.
	// The runner group ID.
	RunnerGroupID *int64 `json:"runnerGroupId,omitempty" tf:"runner_group_id,omitempty"`

	// Machine size for the hosted runner (e.g., "4-core", "8-core"). Can be updated to scale the runner. To list available sizes, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/machine-sizes.
	// Machine size (e.g., '4-core', '8-core'). Can be updated to scale the runner.
	Size *string `json:"size,omitempty" tf:"size,omitempty"`
}

type HostedRunnerObservation struct {

	// The image ID. For GitHub-owned images, use numeric IDs like "2306" for Ubuntu Latest 24.04. To get available images, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/images/github-owned.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Image configuration for the hosted runner. Cannot be changed after creation. Block supports:
	// Image configuration for the hosted runner. Cannot be changed after creation.
	Image []ImageObservation `json:"image,omitempty" tf:"image,omitempty"`

	// Whether this runner should be used to generate custom images. Cannot be changed after creation.
	ImageGen *bool `json:"imageGen,omitempty" tf:"image_gen,omitempty"`

	// The version of the runner image to deploy. This is only relevant for runners using custom images.
	// The version of the runner image to deploy. This is relevant only for runners using custom images.
	ImageVersion *string `json:"imageVersion,omitempty" tf:"image_version,omitempty"`

	// Timestamp (RFC3339) when the runner was last active.
	// Timestamp when the runner was last active.
	LastActiveOn *string `json:"lastActiveOn,omitempty" tf:"last_active_on,omitempty"`

	// Detailed specifications of the machine size:
	// Detailed machine size specifications.
	MachineSizeDetails []MachineSizeDetailsObservation `json:"machineSizeDetails,omitempty" tf:"machine_size_details,omitempty"`

	// Maximum number of runners to scale up to. Runners will not auto-scale above this number. Use this setting to limit costs.
	// Maximum number of runners to scale up to.
	MaximumRunners *int64 `json:"maximumRunners,omitempty" tf:"maximum_runners,omitempty"`

	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain alphanumeric characters, '.', '-', and '_'.
	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Platform of the runner (e.g., "linux-x64", "win-x64").
	// Platform of the runner.
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// Whether to enable static public IP for the runner. Note there are account limits. To list limits, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/limits. Defaults to false.
	// Whether to enable static public IP.
	PublicIPEnabled *bool `json:"publicIpEnabled,omitempty" tf:"public_ip_enabled,omitempty"`

	// List of public IP ranges assigned to this runner (only if public_ip_enabled is true):
	// List of public IP ranges assigned to this runner.
	PublicIps []PublicIpsObservation `json:"publicIps,omitempty" tf:"public_ips,omitempty"`

	// The ID of the runner group to assign this runner to.
	// The runner group ID.
	RunnerGroupID *int64 `json:"runnerGroupId,omitempty" tf:"runner_group_id,omitempty"`

	// Machine size for the hosted runner (e.g., "4-core", "8-core"). Can be updated to scale the runner. To list available sizes, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/machine-sizes.
	// Machine size (e.g., '4-core', '8-core'). Can be updated to scale the runner.
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// Current status of the runner (e.g., "Ready", "Provisioning").
	// Current status of the runner.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type HostedRunnerParameters struct {

	// Image configuration for the hosted runner. Cannot be changed after creation. Block supports:
	// Image configuration for the hosted runner. Cannot be changed after creation.
	// +kubebuilder:validation:Optional
	Image []ImageParameters `json:"image,omitempty" tf:"image,omitempty"`

	// Whether this runner should be used to generate custom images. Cannot be changed after creation.
	// +kubebuilder:validation:Optional
	ImageGen *bool `json:"imageGen,omitempty" tf:"image_gen,omitempty"`

	// The version of the runner image to deploy. This is only relevant for runners using custom images.
	// The version of the runner image to deploy. This is relevant only for runners using custom images.
	// +kubebuilder:validation:Optional
	ImageVersion *string `json:"imageVersion,omitempty" tf:"image_version,omitempty"`

	// Maximum number of runners to scale up to. Runners will not auto-scale above this number. Use this setting to limit costs.
	// Maximum number of runners to scale up to.
	// +kubebuilder:validation:Optional
	MaximumRunners *int64 `json:"maximumRunners,omitempty" tf:"maximum_runners,omitempty"`

	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain alphanumeric characters, '.', '-', and '_'.
	// Name of the hosted runner. Must be between 1 and 64 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to enable static public IP for the runner. Note there are account limits. To list limits, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/limits. Defaults to false.
	// Whether to enable static public IP.
	// +kubebuilder:validation:Optional
	PublicIPEnabled *bool `json:"publicIpEnabled,omitempty" tf:"public_ip_enabled,omitempty"`

	// The ID of the runner group to assign this runner to.
	// The runner group ID.
	// +kubebuilder:validation:Optional
	RunnerGroupID *int64 `json:"runnerGroupId,omitempty" tf:"runner_group_id,omitempty"`

	// Machine size for the hosted runner (e.g., "4-core", "8-core"). Can be updated to scale the runner. To list available sizes, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/machine-sizes.
	// Machine size (e.g., '4-core', '8-core'). Can be updated to scale the runner.
	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`
}

type ImageInitParameters struct {

	// The image ID. For GitHub-owned images, use numeric IDs like "2306" for Ubuntu Latest 24.04. To get available images, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/images/github-owned.
	// The image ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The image source. Valid values are "github", "partner", or "custom". Defaults to "github".
	// The image source (github, partner, or custom).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ImageObservation struct {

	// The image ID. For GitHub-owned images, use numeric IDs like "2306" for Ubuntu Latest 24.04. To get available images, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/images/github-owned.
	// The image ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The size of the image in gigabytes.
	// The size of the image in GB.
	SizeGb *int64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// The image source. Valid values are "github", "partner", or "custom". Defaults to "github".
	// The image source (github, partner, or custom).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ImageParameters struct {

	// The image ID. For GitHub-owned images, use numeric IDs like "2306" for Ubuntu Latest 24.04. To get available images, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/images/github-owned.
	// The image ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The image source. Valid values are "github", "partner", or "custom". Defaults to "github".
	// The image source (github, partner, or custom).
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type MachineSizeDetailsInitParameters struct {
}

type MachineSizeDetailsObservation struct {

	// Number of CPU cores.
	// Number of CPU cores.
	CPUCores *int64 `json:"cpuCores,omitempty" tf:"cpu_cores,omitempty"`

	// The image ID. For GitHub-owned images, use numeric IDs like "2306" for Ubuntu Latest 24.04. To get available images, use the GitHub API: GET /orgs/{org}/actions/hosted-runners/images/github-owned.
	// Machine size ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Amount of memory in gigabytes.
	// Memory in GB.
	MemoryGb *int64 `json:"memoryGb,omitempty" tf:"memory_gb,omitempty"`

	// Amount of storage in gigabytes.
	// Storage in GB.
	StorageGb *int64 `json:"storageGb,omitempty" tf:"storage_gb,omitempty"`
}

type MachineSizeDetailsParameters struct {
}

type PublicIpsInitParameters struct {
}

type PublicIpsObservation struct {

	// Whether this IP range is enabled.
	// Whether this IP range is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Subnet length.
	// Subnet length.
	Length *int64 `json:"length,omitempty" tf:"length,omitempty"`

	// IP address prefix.
	// IP address prefix.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type PublicIpsParameters struct {
}

// HostedRunnerSpec defines the desired state of HostedRunner
type HostedRunnerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HostedRunnerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostedRunnerInitParameters `json:"initProvider,omitempty"`
}

// HostedRunnerStatus defines the observed state of HostedRunner.
type HostedRunnerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HostedRunnerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HostedRunner is the Schema for the HostedRunners API. Creates and manages GitHub-hosted runners within a GitHub organization
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,github}
type HostedRunner struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.image) || (has(self.initProvider) && has(self.initProvider.image))",message="spec.forProvider.image is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runnerGroupId) || (has(self.initProvider) && has(self.initProvider.runnerGroupId))",message="spec.forProvider.runnerGroupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	Spec   HostedRunnerSpec   `json:"spec"`
	Status HostedRunnerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostedRunnerList contains a list of HostedRunners
type HostedRunnerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HostedRunner `json:"items"`
}

// Repository type metadata.
var (
	HostedRunner_Kind             = "HostedRunner"
	HostedRunner_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HostedRunner_Kind}.String()
	HostedRunner_KindAPIVersion   = HostedRunner_Kind + "." + CRDGroupVersion.String()
	HostedRunner_GroupVersionKind = CRDGroupVersion.WithKind(HostedRunner_Kind)
)

func init() {
	SchemeBuilder.Register(&HostedRunner{}, &HostedRunnerList{})
}
